title: "X++ Blog"
author: "Raphael Bucher"
description: "Blog about DFO X++/C# programming"

url: "https://raphaelbucher.ch"

# Email / Social media user names used by the minima theme:
linkedin_username: "rabucher91"

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

gravatar_hash: a1e03f8deb43e75a422903686f1e91f5

kramdown:
  syntax_highlighter_opts:
    disable: true
    
header_pages:
  - resume.html
  - archive.md

plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
